name: Deploy from Dev to Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Dev
      uses: actions/checkout@v2
      with:
        ref: main  # Change to the branch you want to deploy from

    - name: Push to Test
      run: |
        git clone https://github.com/Pooja-manyam/test-1.git
        cd test-1  # The repository was already cloned
        git checkout main  # Change to the branch you want to deploy to in the "Test" repository
        cp -r ${{ github.workspace }}/* ./test-1-copy
        git add .
        git commit -m "Automated push from Dev to Test"
        git push
